package callofdemocracy;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents the status of each state. Each enum has a corresponding value in order to perform the logical operation
 * of switching the neutral state to either republican or democrat.
 */
enum StateStatus {

    WHITE_SQUARE(0), BLACK_SQUARE(1),

    NEUTRAL_ALASKA(50), NEUTRAL_HAWAII(51), NEUTRAL_WASHINGTON(52), NEUTRAL_OREGON(53), NEUTRAL_CALIFORNIA(54),
    NEUTRAL_IDAHO(55), NEUTRAL_NEVADA(56), NEUTRAL_UTAH(57), NEUTRAL_ARIZONA(58), NEUTRAL_MONTANA(59),
    NEUTRAL_WYOMING(60), NEUTRAL_COLORADO(61), NEUTRAL_NEW_MEXICO(62), NEUTRAL_NORTH_DAKOTA(63),
    NEUTRAL_SOUTH_DAKOTA(64), NEUTRAL_NEBRASKA(65), NEUTRAL_KANSAS(66), NEUTRAL_OKLAHOMA(67), NEUTRAL_TEXAS(68),
    NEUTRAL_MINNESOTA(69), NEUTRAL_IOWA(70), NEUTRAL_MISSOURI(71), NEUTRAL_ARKANSAS(72), NEUTRAL_LOUISIANA(73),
    NEUTRAL_WISCONSIN(74), NEUTRAL_ILLINOIS(75), NEUTRAL_MISSISSIPPI(76), NEUTRAL_MICHIGAN(77), NEUTRAL_INDIANA(78),
    NEUTRAL_KENTUCKY(79), NEUTRAL_TENNESSEE(80), NEUTRAL_ALABAMA(81), NEUTRAL_OHIO(82), NEUTRAL_GEORGIA(83),
    NEUTRAL_FLORIDA(84), NEUTRAL_NEW_YORK(85), NEUTRAL_PENNSYLVANIA(86), NEUTRAL_WEST_VIRGINIA(87),
    NEUTRAL_VIRGINIA(88), NEUTRAL_NORTH_CAROLINA(89), NEUTRAL_SOUTH_CAROLINA(90), NEUTRAL_MAINE(91),
    NEUTRAL_VERMONT(92), NEUTRAL_NEW_HAMPSHIRE(93), NEUTRAL_MASSACHUSETTS(94), NEUTRAL_RHODE_ISLAND(95),
    NEUTRAL_CONNECTICUT(96), NEUTRAL_NEW_JERSEY(97), NEUTRAL_DELAWARE(98), NEUTRAL_MARYLAND(99),

    BLUE_ALASKA(100), BLUE_HAWAII(101), BLUE_WASHINGTON(102), BLUE_OREGON(103), BLUE_CALIFORNIA(104), BLUE_IDAHO(105),
    BLUE_NEVADA(106), BLUE_UTAH(107), BLUE_ARIZONA(108), BLUE_MONTANA(109), BLUE_WYOMING(110), BLUE_COLORADO(111),
    BLUE_NEW_MEXICO(112), BLUE_NORTH_DAKOTA(113), BLUE_SOUTH_DAKOTA(114), BLUE_NEBRASKA(115), BLUE_KANSAS(116),
    BLUE_OKLAHOMA(117), BLUE_TEXAS(118), BLUE_MINNESOTA(119), BLUE_IOWA(120), BLUE_MISSOURI(121), BLUE_ARKANSAS(122),
    BLUE_LOUISIANA(123), BLUE_WISCONSIN(124), BLUE_ILLINOIS(125), BLUE_MISSISSIPPI(126), BLUE_MICHIGAN(127),
    BLUE_INDIANA(128), BLUE_KENTUCKY(129), BLUE_TENNESSEE(130), BLUE_ALABAMA(131), BLUE_OHIO(132), BLUE_GEORGIA(133),
    BLUE_FLORIDA(134), BLUE_NEW_YORK(135), BLUE_PENNSYLVANIA(136), BLUE_WEST_VIRGINIA(137), BLUE_VIRGINIA(138),
    BLUE_NORTH_CAROLINA(139), BLUE_SOUTH_CAROLINA(140), BLUE_MAINE(141), BLUE_VERMONT(142), BLUE_NEW_HAMPSHIRE(143),
    BLUE_MASSACHUSETTS(144), BLUE_RHODE_ISLAND(145), BLUE_CONNECTICUT(146), BLUE_NEW_JERSEY(147), BLUE_DELAWARE(148),
    BLUE_MARYLAND(149),

    RED_ALASKA(150), RED_HAWAII(151), RED_WASHINGTON(152), RED_OREGON(153), RED_CALIFORNIA(154), RED_IDAHO(155),
    RED_NEVADA(156), RED_UTAH(157), RED_ARIZONA(158), RED_MONTANA(159), RED_WYOMING(160), RED_COLORADO(161),
    RED_NEW_MEXICO(162), RED_NORTH_DAKOTA(163), RED_SOUTH_DAKOTA(164), RED_NEBRASKA(165), RED_KANSAS(166),
    RED_OKLAHOMA(167), RED_TEXAS(168), RED_MINNESOTA(169), RED_IOWA(170), RED_MISSOURI(171), RED_ARKANSAS(172),
    RED_LOUISIANA(173), RED_WISCONSIN(174), RED_ILLINOIS(175), RED_MISSISSIPPI(176), RED_MICHIGAN(177),
    RED_INDIANA(178), RED_KENTUCKY(179), RED_TENNESSEE(180), RED_ALABAMA(181), RED_OHIO(182), RED_GEORGIA(183),
    RED_FLORIDA(184), RED_NEW_YORK(185), RED_PENNSYLVANIA(186), RED_WEST_VIRGINIA(187), RED_VIRGINIA(188),
    RED_NORTH_CAROLINA(189), RED_SOUTH_CAROLINA(190), RED_MAINE(191), RED_VERMONT(192), RED_NEW_HAMPSHIRE(193),
    RED_MASSACHUSETTS(194), RED_RHODE_ISLAND(195), RED_CONNECTICUT(196), RED_NEW_JERSEY(197), RED_DELAWARE(198),
    RED_MARYLAND(199);

    private int value;
    private static final Map map = new HashMap<>();

    StateStatus(int value) {
        this.value = value;
    }

    static {
        for (StateStatus stateStatus : StateStatus.values()) {
            map.put(stateStatus.value, stateStatus);
        }
    }

    public static StateStatus intToStateStatus(int stateStatus) {
        return (StateStatus) map.get(stateStatus);
    }

    public int stateStatusToInt() {
        return value;
    }
}
